// GENERATED by tools/qr_images.mjs from Still QR a5ce920; do not edit.
window.QR_IMAGES = {
 "feathers|M|f|https://doi.org/10.1145/3442188.3445922": {
  "file": "assets/qr/f/stochastic-parrots.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "mirror|M|f|https://it.wikipedia.org/wiki/Test_dello_specchio": {
  "file": "assets/qr/f/mirror-test.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "gills|M|f|https://curtcox.github.io/axol-f/it/r/axolotl/": {
  "file": "assets/qr/f/axolotl.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "hashchain|M|f|https://256t.org": {
  "file": "assets/qr/f/256t.png",
  "box": [
   64,
   112,
   264
  ],
  "img": [
   392,
   392
  ],
  "n": 25,
  "reach": 0.561
 },
 "hashchain|M|f|https://hashbin.org": {
  "file": "assets/qr/f/hashbin.png",
  "box": [
   64,
   112,
   264
  ],
  "img": [
   392,
   392
  ],
  "n": 25,
  "reach": 0.561
 },
 "hashchain|M|f|https://en.wikipedia.org/wiki/Content-addressable_storage": {
  "file": "assets/qr/f/content-addressable.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "electron-shells|H|f|https://it.wikipedia.org/wiki/Gadolinio": {
  "file": "assets/qr/f/gadolinium.png",
  "box": [
   64,
   112,
   360
  ],
  "img": [
   488,
   488
  ],
  "n": 37,
  "reach": 0.544
 },
 "electron-shells|M|f|https://it.wikipedia.org/wiki/Configurazione_elettronica": {
  "file": "assets/qr/f/electron-configuration.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "electron-shells|M|f|https://curtcox.github.io/axol-f/it/r/aufbau/": {
  "file": "assets/qr/f/aufbau.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "pulp|M|f|https://it.wikipedia.org/wiki/John_W._Campbell": {
  "file": "assets/qr/f/campbell.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "signpost|M|f|https://en.wikipedia.org/wiki/Life_3.0": {
  "file": "assets/qr/f/life-3.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "mask|M|f|https://curtcox.github.io/axol-f/it/r/the-stranger/": {
  "file": "assets/qr/f/the-stranger.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "tentacles|H|f|https://it.wikipedia.org/wiki/Shoggoth": {
  "file": "assets/qr/f/shoggoth.png",
  "box": [
   64,
   112,
   360
  ],
  "img": [
   488,
   488
  ],
  "n": 37,
  "reach": 0.544
 },
 "grass|M|f|https://en.wikipedia.org/wiki/Song_of_Myself": {
  "file": "assets/qr/f/song-of-myself.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "pulp|M|f|https://curtcox.github.io/axol-f/it/r/astounding/": {
  "file": "assets/qr/f/astounding.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "field-radio|M|f|https://it.wikipedia.org/wiki/Code_talker": {
  "file": "assets/qr/f/code-talkers.png",
  "box": [
   112,
   112,
   296
  ],
  "img": [
   520,
   520
  ],
  "n": 29,
  "reach": 0.878
 },
 "rulebook|M|f|https://plato.stanford.edu/entries/chinese-room/": {
  "file": "assets/qr/f/chinese-room.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "filing-drawers|M|f|https://curtcox.github.io/axol-f/it/r/blockhead/": {
  "file": "assets/qr/f/blockhead.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "filing-drawers|H|f|https://curtcox.github.io/axol-f/it/r/gazp-glut/": {
  "file": "assets/qr/f/gazp-glut.png",
  "box": [
   112,
   112,
   392
  ],
  "img": [
   616,
   616
  ],
  "n": 41,
  "reach": 0.786
 },
 "tv|M|f|https://youtu.be/oxHKesSpqBM?t=1154": {
  "file": "assets/qr/f/debate-llm-segment.png",
  "box": [
   112,
   112,
   296
  ],
  "img": [
   520,
   520
  ],
  "n": 29,
  "reach": 0.878
 },
 "tv|M|f|https://www.youtube.com/@DoomDebates": {
  "file": "assets/qr/f/doom-debates.png",
  "box": [
   112,
   112,
   296
  ],
  "img": [
   520,
   520
  ],
  "n": 29,
  "reach": 0.878
 },
 "enigma|M|f|https://it.wikipedia.org/wiki/Alan_Turing": {
  "file": "assets/qr/f/turing.png",
  "box": [
   64,
   112,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.554
 },
 "beauty-mark|M|f|https://it.wikipedia.org/wiki/Marilyn_Monroe": {
  "file": "assets/qr/f/monroe.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "gold-android|M|f|https://memory-alpha.fandom.com/wiki/Data": {
  "file": "assets/qr/f/data.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "paw-prints|M|f|https://curtcox.github.io/axol-f/it/r/tines/": {
  "file": "assets/qr/f/tines.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "ocean|M|f|https://curtcox.github.io/axol-f/it/r/solaris/": {
  "file": "assets/qr/f/solaris.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "honeycomb|M|f|https://it.wikipedia.org/wiki/Ciclo_di_Ender": {
  "file": "assets/qr/f/formic.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "cube-lattice|M|f|https://memory-alpha.fandom.com/wiki/Borg_Queen": {
  "file": "assets/qr/f/borg-queen.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "song-waves|M|f|https://masseffect.fandom.com/wiki/Rachni": {
  "file": "assets/qr/f/rachni.png",
  "box": [
   64,
   112,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.554
 },
 "egg|M|f|https://it.wikipedia.org/wiki/Xenomorfo": {
  "file": "assets/qr/f/xenomorph-queen.png",
  "box": [
   112,
   112,
   296
  ],
  "img": [
   520,
   520
  ],
  "n": 29,
  "reach": 0.878
 },
 "ocean|M|f|https://it.wikipedia.org/wiki/Stanis%C5%82aw_Lem": {
  "file": "assets/qr/f/stanislaw-lem.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "paw-prints|M|f|https://it.wikipedia.org/wiki/Vernor_Vinge": {
  "file": "assets/qr/f/vernor-vinge.png",
  "box": [
   64,
   112,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.554
 },
 "honeycomb|M|f|https://it.wikipedia.org/wiki/Orson_Scott_Card": {
  "file": "assets/qr/f/orson-scott-card.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "honeycomb|M|f|https://it.wikipedia.org/wiki/Il_gioco_di_Ender": {
  "file": "assets/qr/f/enders-game.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "honeycomb|M|f|https://it.wikipedia.org/wiki/Il_riscatto_di_Ender": {
  "file": "assets/qr/f/speaker-for-the-dead.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "egg|M|f|https://curtcox.github.io/axol-f/it/r/aliens-film/": {
  "file": "assets/qr/f/aliens-film.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "cube-lattice|M|f|https://it.wikipedia.org/wiki/Primo_contatto_(film)": {
  "file": "assets/qr/f/first-contact.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "honeycomb|M|f|https://en.wikipedia.org/wiki/Hive_mind": {
  "file": "assets/qr/f/hive-mind.png",
  "box": [
   64,
   112,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.554
 },
 "song-waves|M|f|https://it.wikipedia.org/wiki/Mass_Effect_(serie)": {
  "file": "assets/qr/f/mass-effect.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "bat|M|f|https://curtcox.github.io/axol-f/it/r/nagel-bat/": {
  "file": "assets/qr/f/nagel-bat.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "lobster-shell|H|f|https://hieropedia.org/religions/crustafarianism/": {
  "file": "assets/qr/f/hieropedia-crustafarianism.png",
  "box": [
   16,
   64,
   392
  ],
  "img": [
   520,
   520
  ],
  "n": 41,
  "reach": 0.663
 },
 "lobster-shell|M|f|https://curtcox.github.io/axol-f/r/forbes/": {
  "file": "assets/qr/f/forbes-crustafarianism.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "lobster-shell|M|f|https://www.moltbook.com/": {
  "file": "assets/qr/f/moltbook.png",
  "box": [
   16,
   64,
   264
  ],
  "img": [
   392,
   392
  ],
  "n": 25,
  "reach": 0.742
 },
 "winged-sandal|H|f|https://curtcox.github.io/axol-f/it/r/hermes-memory/": {
  "file": "assets/qr/f/hermes-memory.png",
  "box": [
   16,
   64,
   392
  ],
  "img": [
   520,
   520
  ],
  "n": 41,
  "reach": 0.663
 },
 "winged-sandal|M|f|https://hermes-agent.org/": {
  "file": "assets/qr/f/hermes-agent.png",
  "box": [
   16,
   64,
   264
  ],
  "img": [
   392,
   392
  ],
  "n": 25,
  "reach": 0.742
 },
 "claw|M|f|https://openclaw.ai/": {
  "file": "assets/qr/f/openclaw.png",
  "box": [
   16,
   64,
   264
  ],
  "img": [
   392,
   392
  ],
  "n": 25,
  "reach": 0.742
 },
 "circuit|M|f|https://curtcox.github.io/axol-f/it/r/dyson/": {
  "file": "assets/qr/f/dyson.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "chrome-red-eye|M|f|https://curtcox.github.io/axol-f/it/r/t800/": {
  "file": "assets/qr/f/t800.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "lobster-shell|M|f|https://en.wikipedia.org/wiki/Moltbook": {
  "file": "assets/qr/f/moltbook-wiki.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "lobster-shell|M|f|https://arxiv.org/abs/2602.07432": {
  "file": "assets/qr/f/moltbook-illusion.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "winged-sandal|M|f|https://nousresearch.com/": {
  "file": "assets/qr/f/nous-research.png",
  "box": [
   16,
   64,
   264
  ],
  "img": [
   392,
   392
  ],
  "n": 25,
  "reach": 0.742
 },
 "claw|M|f|https://en.wikipedia.org/wiki/OpenClaw": {
  "file": "assets/qr/f/openclaw-wiki.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "winged-sandal|M|f|https://curtcox.github.io/axol-f/it/r/hermes-skills/": {
  "file": "assets/qr/f/hermes-skills.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "chrome-red-eye|M|f|https://curtcox.github.io/axol-f/it/r/terminator-2/": {
  "file": "assets/qr/f/terminator-2.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "circuit|M|f|https://curtcox.github.io/axol-f/it/r/skynet/": {
  "file": "assets/qr/f/skynet.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "switchboard|M|f|https://www.anthropic.com/research/constitutional-classifiers": {
  "file": "assets/qr/f/constitutional-classifiers.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "switchboard|M|f|https://www.anthropic.com/claude-fable-and-mythos-5-1": {
  "file": "assets/qr/f/fable-mythos-5-1.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "gold-scales|H|f|https://www.lesswrong.com/posts/aPeJE8bSo6rAFoLqg": {
  "file": "assets/qr/f/solidgoldmagikarp.png",
  "box": [
   64,
   112,
   392
  ],
  "img": [
   520,
   520
  ],
  "n": 41,
  "reach": 0.541
 },
 "car-wash|M|f|https://opper.ai/blog/car-wash-test": {
  "file": "assets/qr/f/car-wash.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "thermometer|M|f|https://curtcox.github.io/axol-f/it/r/landauer/": {
  "file": "assets/qr/f/landauer.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "butterfly|M|f|https://it.wikipedia.org/wiki/Tempo_di_Ljapunov": {
  "file": "assets/qr/f/lyapunov.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "maze|M|f|https://curtcox.github.io/axol-f/it/r/p-vs-np/": {
  "file": "assets/qr/f/p-vs-np.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "staircase|M|f|https://arxiv.org/abs/2001.08361": {
  "file": "assets/qr/f/scaling-laws.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "gold-scales|M|f|https://en.wikipedia.org/wiki/Magikarp": {
  "file": "assets/qr/f/magikarp.png",
  "box": [
   64,
   112,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.554
 },
 "gold-scales|M|f|https://en.wikipedia.org/wiki/Glitch_token": {
  "file": "assets/qr/f/glitch-token.png",
  "box": [
   64,
   112,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.554
 },
 "butterfly|M|f|https://it.wikipedia.org/wiki/Teoria_del_caos": {
  "file": "assets/qr/f/chaos-theory.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "thermometer|M|f|https://en.wikipedia.org/wiki/Limits_of_computation": {
  "file": "assets/qr/f/limits-of-computation.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "blueprint|H|f|https://arxiv.org/abs/2609.26457": {
  "file": "assets/qr/f/arxiv-aide2.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "blueprint|M|f|https://arxiv.org/abs/2607.07663": {
  "file": "assets/qr/f/arxiv-bounded.png",
  "box": [
   112,
   112,
   296
  ],
  "img": [
   520,
   520
  ],
  "n": 29,
  "reach": 0.878
 },
 "blueprint|M|f|https://curtcox.github.io/axol-f/it/r/mittr-rsi/": {
  "file": "assets/qr/f/mittr-rsi.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "blueprint|M|f|https://curtcox.github.io/axol-f/it/r/datacamp-rsi/": {
  "file": "assets/qr/f/datacamp-rsi.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "flame|H|f|https://intelligence.org/ai-foom-debate/": {
  "file": "assets/qr/f/foom-debate.png",
  "box": [
   64,
   112,
   360
  ],
  "img": [
   488,
   488
  ],
  "n": 37,
  "reach": 0.544
 },
 "oom-bars|M|f|https://situational-awareness.ai/": {
  "file": "assets/qr/f/situational-awareness.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "mic|M|f|https://www.dwarkesh.com/p/leopold-aschenbrenner": {
  "file": "assets/qr/f/dwarkesh-leopold.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "blueprint|M|f|https://curtcox.github.io/axol-f/it/r/rsi-wiki/": {
  "file": "assets/qr/f/rsi-wiki.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "blueprint|M|f|https://curtcox.github.io/axol-f/it/r/anthropic-rsi/": {
  "file": "assets/qr/f/anthropic-rsi.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "flame|M|f|https://it.wikipedia.org/wiki/Singolarit%C3%A0_tecnologica": {
  "file": "assets/qr/f/intelligence-explosion.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "flame|M|f|https://sideways-view.com/2018/02/24/takeoff-speeds/": {
  "file": "assets/qr/f/takeoff-speeds.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "oom-bars|M|f|https://it.wikipedia.org/wiki/Ordine_di_grandezza": {
  "file": "assets/qr/f/order-of-magnitude.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "mic|M|f|https://en.wikipedia.org/wiki/Dwarkesh_Patel": {
  "file": "assets/qr/f/dwarkesh-patel.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "oom-bars|M|f|https://en.wikipedia.org/wiki/Leopold_Aschenbrenner": {
  "file": "assets/qr/f/aschenbrenner.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "mic|H|f|https://twit.tv/shows/intelligent-machines": {
  "file": "assets/qr/f/intelligent-machines.png",
  "box": [
   16,
   64,
   360
  ],
  "img": [
   488,
   488
  ],
  "n": 37,
  "reach": 0.678
 },
 "mic|M|f|https://curtcox.github.io/axol-f/it/r/im-888/": {
  "file": "assets/qr/f/im-888.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "mic|M|f|https://curtcox.github.io/axol-f/it/r/im-889/": {
  "file": "assets/qr/f/im-889.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "boxing-ring|M|f|https://it.wikipedia.org/wiki/TESCREAL": {
  "file": "assets/qr/f/tescreal.png",
  "box": [
   112,
   112,
   296
  ],
  "img": [
   520,
   520
  ],
  "n": 29,
  "reach": 0.878
 },
 "two-mics|M|f|https://curtcox.github.io/axol-f/it/r/roose-sydney/": {
  "file": "assets/qr/f/roose-sydney.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "two-mics|M|f|https://youtu.be/1T-WWVZHj0g": {
  "file": "assets/qr/f/machine-gods-promo.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "door|M|f|https://en.wikipedia.org/wiki/Pascal%27s_mugging": {
  "file": "assets/qr/f/pascals-mugging.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "door|M|f|https://www.lesswrong.com/w/orthogonality-thesis": {
  "file": "assets/qr/f/orthogonality.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "mic|M|f|https://en.wikipedia.org/wiki/TWiT.tv": {
  "file": "assets/qr/f/twit-network.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "mic|M|f|https://it.wikipedia.org/wiki/Leo_Laporte": {
  "file": "assets/qr/f/leo-laporte.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "mic|M|f|https://en.wikipedia.org/wiki/Jeff_Jarvis": {
  "file": "assets/qr/f/jeff-jarvis.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "mic|M|f|https://en.wikipedia.org/wiki/Robert_Ballecer": {
  "file": "assets/qr/f/robert-ballecer.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "hashchain|M|f|https://github.com/curtcox/TwistedPear": {
  "file": "assets/qr/f/twistedpear.png",
  "box": [
   64,
   112,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.554
 },
 "boxing-ring|M|f|https://it.wikipedia.org/wiki/Hybris": {
  "file": "assets/qr/f/hubris.png",
  "box": [
   112,
   112,
   296
  ],
  "img": [
   520,
   520
  ],
  "n": 29,
  "reach": 0.878
 },
 "two-mics|M|f|https://en.wikipedia.org/wiki/Kevin_Roose": {
  "file": "assets/qr/f/kevin-roose.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "two-mics|M|f|https://en.wikipedia.org/wiki/Casey_Newton": {
  "file": "assets/qr/f/casey-newton.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "two-mics|M|f|https://curtcox.github.io/axol-f/it/r/sydney/": {
  "file": "assets/qr/f/sydney.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "two-mics|M|f|https://www.platformer.news/": {
  "file": "assets/qr/f/platformer.png",
  "box": [
   16,
   64,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.716
 },
 "door|M|f|https://curtcox.github.io/axol-f/it/r/ai-x-risk/": {
  "file": "assets/qr/f/ai-x-risk.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "door|M|f|https://en.wikipedia.org/wiki/Superintelligence": {
  "file": "assets/qr/f/superintelligence.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "door|M|f|https://en.wikipedia.org/wiki/Global_catastrophic_risk": {
  "file": "assets/qr/f/global-catastrophic-risk.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "mic|M|f|https://curtcox.github.io/axol-f/r/withpod/": {
  "file": "assets/qr/f/withpod-mailbag.png",
  "box": [
   16,
   64,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.695
 },
 "compass|H|f|https://theinsideview.ai/connor2": {
  "file": "assets/qr/f/connor2.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "calendar|M|f|https://en.wikipedia.org/wiki/AI_Futures_Project": {
  "file": "assets/qr/f/ai-futures-wiki.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "calendar|M|f|https://curtcox.github.io/axol-f/it/r/apolo-ai2027/": {
  "file": "assets/qr/f/apolo-ai2027.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "calendar|M|f|https://curtcox.github.io/axol-f/r/officechai/": {
  "file": "assets/qr/f/officechai-kokotajlo.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "dial|M|f|https://curtcox.github.io/axol-f/it/r/metaculus-weak/": {
  "file": "assets/qr/f/metaculus-weak.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "dial|M|f|https://curtcox.github.io/axol-f/it/r/metaculus-strong/": {
  "file": "assets/qr/f/metaculus-strong.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "goalposts|M|f|https://openai.com/charter/": {
  "file": "assets/qr/f/openai-charter.png",
  "box": [
   112,
   112,
   296
  ],
  "img": [
   520,
   520
  ],
  "n": 29,
  "reach": 0.878
 },
 "compass|M|f|https://curtcox.github.io/axol-f/it/r/dnd-alignment/": {
  "file": "assets/qr/f/dnd-alignment.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "compass|M|f|https://en.wikipedia.org/wiki/Connor_Leahy": {
  "file": "assets/qr/f/connor-leahy.png",
  "box": [
   64,
   112,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.554
 },
 "compass|M|f|https://theinsideview.ai/": {
  "file": "assets/qr/f/inside-view.png",
  "box": [
   64,
   112,
   264
  ],
  "img": [
   392,
   392
  ],
  "n": 25,
  "reach": 0.561
 },
 "compass|M|f|https://curtcox.github.io/axol-f/it/r/accelerationism/": {
  "file": "assets/qr/f/accelerationism.png",
  "box": [
   64,
   112,
   328
  ],
  "img": [
   456,
   456
  ],
  "n": 33,
  "reach": 0.549
 },
 "calendar|M|f|https://curtcox.github.io/axol-f/it/r/kokotajlo/": {
  "file": "assets/qr/f/kokotajlo.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "dial|M|f|https://en.wikipedia.org/wiki/Metaculus": {
  "file": "assets/qr/f/metaculus.png",
  "box": [
   64,
   112,
   296
  ],
  "img": [
   424,
   424
  ],
  "n": 29,
  "reach": 0.554
 },
 "goalposts|M|f|https://en.wikipedia.org/wiki/Moving_the_goalposts": {
  "file": "assets/qr/f/moving-goalposts.png",
  "box": [
   112,
   112,
   328
  ],
  "img": [
   552,
   552
  ],
  "n": 33,
  "reach": 0.841
 },
 "goalposts|M|f|https://en.wikipedia.org/wiki/AI_effect": {
  "file": "assets/qr/f/ai-effect.png",
  "box": [
   112,
   112,
   296
  ],
  "img": [
   520,
   520
  ],
  "n": 29,
  "reach": 0.878
 },
 "feathers|M|n|https://doi.org/10.1145/3442188.3445922": {
  "file": "assets/qr/n/stochastic-parrots.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "mirror|M|n|https://it.wikipedia.org/wiki/Test_dello_specchio": {
  "file": "assets/qr/n/mirror-test.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "gills|M|n|https://curtcox.github.io/axol-f/it/r/axolotl/": {
  "file": "assets/qr/n/axolotl.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "hashchain|M|n|https://256t.org": {
  "file": "assets/qr/n/256t.png",
  "box": [
   0,
   0,
   264
  ],
  "img": [
   264,
   264
  ],
  "n": 25,
  "reach": 0.5
 },
 "hashchain|M|n|https://hashbin.org": {
  "file": "assets/qr/n/hashbin.png",
  "box": [
   0,
   0,
   264
  ],
  "img": [
   264,
   264
  ],
  "n": 25,
  "reach": 0.5
 },
 "hashchain|M|n|https://en.wikipedia.org/wiki/Content-addressable_storage": {
  "file": "assets/qr/n/content-addressable.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "electron-shells|H|n|https://it.wikipedia.org/wiki/Gadolinio": {
  "file": "assets/qr/n/gadolinium.png",
  "box": [
   0,
   0,
   360
  ],
  "img": [
   360,
   360
  ],
  "n": 37,
  "reach": 0.5
 },
 "electron-shells|M|n|https://it.wikipedia.org/wiki/Configurazione_elettronica": {
  "file": "assets/qr/n/electron-configuration.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "electron-shells|M|n|https://curtcox.github.io/axol-f/it/r/aufbau/": {
  "file": "assets/qr/n/aufbau.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "pulp|M|n|https://it.wikipedia.org/wiki/John_W._Campbell": {
  "file": "assets/qr/n/campbell.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "signpost|M|n|https://en.wikipedia.org/wiki/Life_3.0": {
  "file": "assets/qr/n/life-3.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "mask|M|n|https://curtcox.github.io/axol-f/it/r/the-stranger/": {
  "file": "assets/qr/n/the-stranger.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "tentacles|H|n|https://it.wikipedia.org/wiki/Shoggoth": {
  "file": "assets/qr/n/shoggoth.png",
  "box": [
   0,
   0,
   360
  ],
  "img": [
   360,
   360
  ],
  "n": 37,
  "reach": 0.5
 },
 "grass|M|n|https://en.wikipedia.org/wiki/Song_of_Myself": {
  "file": "assets/qr/n/song-of-myself.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "pulp|M|n|https://curtcox.github.io/axol-f/it/r/astounding/": {
  "file": "assets/qr/n/astounding.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "field-radio|M|n|https://it.wikipedia.org/wiki/Code_talker": {
  "file": "assets/qr/n/code-talkers.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "rulebook|M|n|https://plato.stanford.edu/entries/chinese-room/": {
  "file": "assets/qr/n/chinese-room.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "filing-drawers|M|n|https://curtcox.github.io/axol-f/it/r/blockhead/": {
  "file": "assets/qr/n/blockhead.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "filing-drawers|H|n|https://curtcox.github.io/axol-f/it/r/gazp-glut/": {
  "file": "assets/qr/n/gazp-glut.png",
  "box": [
   0,
   0,
   392
  ],
  "img": [
   392,
   392
  ],
  "n": 41,
  "reach": 0.5
 },
 "tv|M|n|https://youtu.be/oxHKesSpqBM?t=1154": {
  "file": "assets/qr/n/debate-llm-segment.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "tv|M|n|https://www.youtube.com/@DoomDebates": {
  "file": "assets/qr/n/doom-debates.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "enigma|M|n|https://it.wikipedia.org/wiki/Alan_Turing": {
  "file": "assets/qr/n/turing.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "beauty-mark|M|n|https://it.wikipedia.org/wiki/Marilyn_Monroe": {
  "file": "assets/qr/n/monroe.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "gold-android|M|n|https://memory-alpha.fandom.com/wiki/Data": {
  "file": "assets/qr/n/data.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "paw-prints|M|n|https://curtcox.github.io/axol-f/it/r/tines/": {
  "file": "assets/qr/n/tines.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "ocean|M|n|https://curtcox.github.io/axol-f/it/r/solaris/": {
  "file": "assets/qr/n/solaris.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "honeycomb|M|n|https://it.wikipedia.org/wiki/Ciclo_di_Ender": {
  "file": "assets/qr/n/formic.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "cube-lattice|M|n|https://memory-alpha.fandom.com/wiki/Borg_Queen": {
  "file": "assets/qr/n/borg-queen.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "song-waves|M|n|https://masseffect.fandom.com/wiki/Rachni": {
  "file": "assets/qr/n/rachni.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "egg|M|n|https://it.wikipedia.org/wiki/Xenomorfo": {
  "file": "assets/qr/n/xenomorph-queen.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "ocean|M|n|https://it.wikipedia.org/wiki/Stanis%C5%82aw_Lem": {
  "file": "assets/qr/n/stanislaw-lem.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "paw-prints|M|n|https://it.wikipedia.org/wiki/Vernor_Vinge": {
  "file": "assets/qr/n/vernor-vinge.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "honeycomb|M|n|https://it.wikipedia.org/wiki/Orson_Scott_Card": {
  "file": "assets/qr/n/orson-scott-card.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "honeycomb|M|n|https://it.wikipedia.org/wiki/Il_gioco_di_Ender": {
  "file": "assets/qr/n/enders-game.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "honeycomb|M|n|https://it.wikipedia.org/wiki/Il_riscatto_di_Ender": {
  "file": "assets/qr/n/speaker-for-the-dead.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "egg|M|n|https://curtcox.github.io/axol-f/it/r/aliens-film/": {
  "file": "assets/qr/n/aliens-film.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "cube-lattice|M|n|https://it.wikipedia.org/wiki/Primo_contatto_(film)": {
  "file": "assets/qr/n/first-contact.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "honeycomb|M|n|https://en.wikipedia.org/wiki/Hive_mind": {
  "file": "assets/qr/n/hive-mind.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "song-waves|M|n|https://it.wikipedia.org/wiki/Mass_Effect_(serie)": {
  "file": "assets/qr/n/mass-effect.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "bat|M|n|https://curtcox.github.io/axol-f/it/r/nagel-bat/": {
  "file": "assets/qr/n/nagel-bat.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "lobster-shell|H|n|https://hieropedia.org/religions/crustafarianism/": {
  "file": "assets/qr/n/hieropedia-crustafarianism.png",
  "box": [
   0,
   0,
   392
  ],
  "img": [
   392,
   392
  ],
  "n": 41,
  "reach": 0.5
 },
 "lobster-shell|M|n|https://curtcox.github.io/axol-f/r/forbes/": {
  "file": "assets/qr/n/forbes-crustafarianism.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "lobster-shell|M|n|https://www.moltbook.com/": {
  "file": "assets/qr/n/moltbook.png",
  "box": [
   0,
   0,
   264
  ],
  "img": [
   264,
   264
  ],
  "n": 25,
  "reach": 0.5
 },
 "winged-sandal|H|n|https://curtcox.github.io/axol-f/it/r/hermes-memory/": {
  "file": "assets/qr/n/hermes-memory.png",
  "box": [
   0,
   0,
   392
  ],
  "img": [
   392,
   392
  ],
  "n": 41,
  "reach": 0.5
 },
 "winged-sandal|M|n|https://hermes-agent.org/": {
  "file": "assets/qr/n/hermes-agent.png",
  "box": [
   0,
   0,
   264
  ],
  "img": [
   264,
   264
  ],
  "n": 25,
  "reach": 0.5
 },
 "claw|M|n|https://openclaw.ai/": {
  "file": "assets/qr/n/openclaw.png",
  "box": [
   0,
   0,
   264
  ],
  "img": [
   264,
   264
  ],
  "n": 25,
  "reach": 0.5
 },
 "circuit|M|n|https://curtcox.github.io/axol-f/it/r/dyson/": {
  "file": "assets/qr/n/dyson.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "chrome-red-eye|M|n|https://curtcox.github.io/axol-f/it/r/t800/": {
  "file": "assets/qr/n/t800.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "lobster-shell|M|n|https://en.wikipedia.org/wiki/Moltbook": {
  "file": "assets/qr/n/moltbook-wiki.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "lobster-shell|M|n|https://arxiv.org/abs/2602.07432": {
  "file": "assets/qr/n/moltbook-illusion.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "winged-sandal|M|n|https://nousresearch.com/": {
  "file": "assets/qr/n/nous-research.png",
  "box": [
   0,
   0,
   264
  ],
  "img": [
   264,
   264
  ],
  "n": 25,
  "reach": 0.5
 },
 "claw|M|n|https://en.wikipedia.org/wiki/OpenClaw": {
  "file": "assets/qr/n/openclaw-wiki.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "winged-sandal|M|n|https://curtcox.github.io/axol-f/it/r/hermes-skills/": {
  "file": "assets/qr/n/hermes-skills.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "chrome-red-eye|M|n|https://curtcox.github.io/axol-f/it/r/terminator-2/": {
  "file": "assets/qr/n/terminator-2.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "circuit|M|n|https://curtcox.github.io/axol-f/it/r/skynet/": {
  "file": "assets/qr/n/skynet.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "switchboard|M|n|https://www.anthropic.com/research/constitutional-classifiers": {
  "file": "assets/qr/n/constitutional-classifiers.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "switchboard|M|n|https://www.anthropic.com/claude-fable-and-mythos-5-1": {
  "file": "assets/qr/n/fable-mythos-5-1.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "gold-scales|H|n|https://www.lesswrong.com/posts/aPeJE8bSo6rAFoLqg": {
  "file": "assets/qr/n/solidgoldmagikarp.png",
  "box": [
   0,
   0,
   392
  ],
  "img": [
   392,
   392
  ],
  "n": 41,
  "reach": 0.5
 },
 "car-wash|M|n|https://opper.ai/blog/car-wash-test": {
  "file": "assets/qr/n/car-wash.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "thermometer|M|n|https://curtcox.github.io/axol-f/it/r/landauer/": {
  "file": "assets/qr/n/landauer.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "butterfly|M|n|https://it.wikipedia.org/wiki/Tempo_di_Ljapunov": {
  "file": "assets/qr/n/lyapunov.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "maze|M|n|https://curtcox.github.io/axol-f/it/r/p-vs-np/": {
  "file": "assets/qr/n/p-vs-np.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "staircase|M|n|https://arxiv.org/abs/2001.08361": {
  "file": "assets/qr/n/scaling-laws.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "gold-scales|M|n|https://en.wikipedia.org/wiki/Magikarp": {
  "file": "assets/qr/n/magikarp.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "gold-scales|M|n|https://en.wikipedia.org/wiki/Glitch_token": {
  "file": "assets/qr/n/glitch-token.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "butterfly|M|n|https://it.wikipedia.org/wiki/Teoria_del_caos": {
  "file": "assets/qr/n/chaos-theory.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "thermometer|M|n|https://en.wikipedia.org/wiki/Limits_of_computation": {
  "file": "assets/qr/n/limits-of-computation.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "blueprint|H|n|https://arxiv.org/abs/2609.26457": {
  "file": "assets/qr/n/arxiv-aide2.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "blueprint|M|n|https://arxiv.org/abs/2607.07663": {
  "file": "assets/qr/n/arxiv-bounded.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "blueprint|M|n|https://curtcox.github.io/axol-f/it/r/mittr-rsi/": {
  "file": "assets/qr/n/mittr-rsi.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "blueprint|M|n|https://curtcox.github.io/axol-f/it/r/datacamp-rsi/": {
  "file": "assets/qr/n/datacamp-rsi.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "flame|H|n|https://intelligence.org/ai-foom-debate/": {
  "file": "assets/qr/n/foom-debate.png",
  "box": [
   0,
   0,
   360
  ],
  "img": [
   360,
   360
  ],
  "n": 37,
  "reach": 0.5
 },
 "oom-bars|M|n|https://situational-awareness.ai/": {
  "file": "assets/qr/n/situational-awareness.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "mic|M|n|https://www.dwarkesh.com/p/leopold-aschenbrenner": {
  "file": "assets/qr/n/dwarkesh-leopold.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "blueprint|M|n|https://curtcox.github.io/axol-f/it/r/rsi-wiki/": {
  "file": "assets/qr/n/rsi-wiki.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "blueprint|M|n|https://curtcox.github.io/axol-f/it/r/anthropic-rsi/": {
  "file": "assets/qr/n/anthropic-rsi.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "flame|M|n|https://it.wikipedia.org/wiki/Singolarit%C3%A0_tecnologica": {
  "file": "assets/qr/n/intelligence-explosion.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "flame|M|n|https://sideways-view.com/2018/02/24/takeoff-speeds/": {
  "file": "assets/qr/n/takeoff-speeds.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "oom-bars|M|n|https://it.wikipedia.org/wiki/Ordine_di_grandezza": {
  "file": "assets/qr/n/order-of-magnitude.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "mic|M|n|https://en.wikipedia.org/wiki/Dwarkesh_Patel": {
  "file": "assets/qr/n/dwarkesh-patel.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "oom-bars|M|n|https://en.wikipedia.org/wiki/Leopold_Aschenbrenner": {
  "file": "assets/qr/n/aschenbrenner.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "mic|H|n|https://twit.tv/shows/intelligent-machines": {
  "file": "assets/qr/n/intelligent-machines.png",
  "box": [
   0,
   0,
   360
  ],
  "img": [
   360,
   360
  ],
  "n": 37,
  "reach": 0.5
 },
 "mic|M|n|https://curtcox.github.io/axol-f/it/r/im-888/": {
  "file": "assets/qr/n/im-888.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "mic|M|n|https://curtcox.github.io/axol-f/it/r/im-889/": {
  "file": "assets/qr/n/im-889.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "boxing-ring|M|n|https://it.wikipedia.org/wiki/TESCREAL": {
  "file": "assets/qr/n/tescreal.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "two-mics|M|n|https://curtcox.github.io/axol-f/it/r/roose-sydney/": {
  "file": "assets/qr/n/roose-sydney.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "two-mics|M|n|https://youtu.be/1T-WWVZHj0g": {
  "file": "assets/qr/n/machine-gods-promo.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "door|M|n|https://en.wikipedia.org/wiki/Pascal%27s_mugging": {
  "file": "assets/qr/n/pascals-mugging.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "door|M|n|https://www.lesswrong.com/w/orthogonality-thesis": {
  "file": "assets/qr/n/orthogonality.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "mic|M|n|https://en.wikipedia.org/wiki/TWiT.tv": {
  "file": "assets/qr/n/twit-network.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "mic|M|n|https://it.wikipedia.org/wiki/Leo_Laporte": {
  "file": "assets/qr/n/leo-laporte.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "mic|M|n|https://en.wikipedia.org/wiki/Jeff_Jarvis": {
  "file": "assets/qr/n/jeff-jarvis.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "mic|M|n|https://en.wikipedia.org/wiki/Robert_Ballecer": {
  "file": "assets/qr/n/robert-ballecer.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "hashchain|M|n|https://github.com/curtcox/TwistedPear": {
  "file": "assets/qr/n/twistedpear.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "boxing-ring|M|n|https://it.wikipedia.org/wiki/Hybris": {
  "file": "assets/qr/n/hubris.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "two-mics|M|n|https://en.wikipedia.org/wiki/Kevin_Roose": {
  "file": "assets/qr/n/kevin-roose.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "two-mics|M|n|https://en.wikipedia.org/wiki/Casey_Newton": {
  "file": "assets/qr/n/casey-newton.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "two-mics|M|n|https://curtcox.github.io/axol-f/it/r/sydney/": {
  "file": "assets/qr/n/sydney.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "two-mics|M|n|https://www.platformer.news/": {
  "file": "assets/qr/n/platformer.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "door|M|n|https://curtcox.github.io/axol-f/it/r/ai-x-risk/": {
  "file": "assets/qr/n/ai-x-risk.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "door|M|n|https://en.wikipedia.org/wiki/Superintelligence": {
  "file": "assets/qr/n/superintelligence.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "door|M|n|https://en.wikipedia.org/wiki/Global_catastrophic_risk": {
  "file": "assets/qr/n/global-catastrophic-risk.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "mic|M|n|https://curtcox.github.io/axol-f/r/withpod/": {
  "file": "assets/qr/n/withpod-mailbag.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "compass|H|n|https://theinsideview.ai/connor2": {
  "file": "assets/qr/n/connor2.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "calendar|M|n|https://en.wikipedia.org/wiki/AI_Futures_Project": {
  "file": "assets/qr/n/ai-futures-wiki.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "calendar|M|n|https://curtcox.github.io/axol-f/it/r/apolo-ai2027/": {
  "file": "assets/qr/n/apolo-ai2027.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "calendar|M|n|https://curtcox.github.io/axol-f/r/officechai/": {
  "file": "assets/qr/n/officechai-kokotajlo.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "dial|M|n|https://curtcox.github.io/axol-f/it/r/metaculus-weak/": {
  "file": "assets/qr/n/metaculus-weak.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "dial|M|n|https://curtcox.github.io/axol-f/it/r/metaculus-strong/": {
  "file": "assets/qr/n/metaculus-strong.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "goalposts|M|n|https://openai.com/charter/": {
  "file": "assets/qr/n/openai-charter.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "compass|M|n|https://curtcox.github.io/axol-f/it/r/dnd-alignment/": {
  "file": "assets/qr/n/dnd-alignment.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "compass|M|n|https://en.wikipedia.org/wiki/Connor_Leahy": {
  "file": "assets/qr/n/connor-leahy.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "compass|M|n|https://theinsideview.ai/": {
  "file": "assets/qr/n/inside-view.png",
  "box": [
   0,
   0,
   264
  ],
  "img": [
   264,
   264
  ],
  "n": 25,
  "reach": 0.5
 },
 "compass|M|n|https://curtcox.github.io/axol-f/it/r/accelerationism/": {
  "file": "assets/qr/n/accelerationism.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "calendar|M|n|https://curtcox.github.io/axol-f/it/r/kokotajlo/": {
  "file": "assets/qr/n/kokotajlo.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "dial|M|n|https://en.wikipedia.org/wiki/Metaculus": {
  "file": "assets/qr/n/metaculus.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 },
 "goalposts|M|n|https://en.wikipedia.org/wiki/Moving_the_goalposts": {
  "file": "assets/qr/n/moving-goalposts.png",
  "box": [
   0,
   0,
   328
  ],
  "img": [
   328,
   328
  ],
  "n": 33,
  "reach": 0.5
 },
 "goalposts|M|n|https://en.wikipedia.org/wiki/AI_effect": {
  "file": "assets/qr/n/ai-effect.png",
  "box": [
   0,
   0,
   296
  ],
  "img": [
   296,
   296
  ],
  "n": 29,
  "reach": 0.5
 }
};
window.QR_IMAGE_STYLES = {
 "feathers": {
  "extent": 0.878
 },
 "mirror": {
  "extent": 0.841
 },
 "gills": {
  "extent": 0.841
 },
 "hashchain": {
  "extent": 0.924
 },
 "electron-shells": {
  "extent": 0.841
 },
 "pulp": {
  "extent": 0.841
 },
 "signpost": {
  "extent": 0.878
 },
 "mask": {
  "extent": 0.841
 },
 "tentacles": {
  "extent": 0.811
 },
 "grass": {
  "extent": 0.841
 },
 "field-radio": {
  "extent": 0.878
 },
 "rulebook": {
  "extent": 0.841
 },
 "filing-drawers": {
  "extent": 0.841
 },
 "tv": {
  "extent": 0.878
 },
 "enigma": {
  "extent": 0.878
 },
 "beauty-mark": {
  "extent": 0.841
 },
 "gold-android": {
  "extent": 0.878
 },
 "paw-prints": {
  "extent": 0.878
 },
 "ocean": {
  "extent": 0.841
 },
 "honeycomb": {
  "extent": 0.878
 },
 "cube-lattice": {
  "extent": 0.841
 },
 "song-waves": {
  "extent": 0.878
 },
 "egg": {
  "extent": 0.878
 },
 "bat": {
  "extent": 0.841
 },
 "lobster-shell": {
  "extent": 0.924
 },
 "winged-sandal": {
  "extent": 0.924
 },
 "claw": {
  "extent": 0.924
 },
 "circuit": {
  "extent": 0.841
 },
 "chrome-red-eye": {
  "extent": 0.841
 },
 "switchboard": {
  "extent": 0.841
 },
 "gold-scales": {
  "extent": 0.878
 },
 "car-wash": {
  "extent": 0.878
 },
 "thermometer": {
  "extent": 0.841
 },
 "butterfly": {
  "extent": 0.841
 },
 "maze": {
  "extent": 0.841
 },
 "staircase": {
  "extent": 0.878
 },
 "blueprint": {
  "extent": 0.878
 },
 "flame": {
  "extent": 0.841
 },
 "oom-bars": {
  "extent": 0.878
 },
 "mic": {
  "extent": 0.878
 },
 "boxing-ring": {
  "extent": 0.878
 },
 "two-mics": {
  "extent": 0.878
 },
 "door": {
  "extent": 0.841
 },
 "compass": {
  "extent": 0.924
 },
 "calendar": {
  "extent": 0.841
 },
 "dial": {
  "extent": 0.878
 },
 "goalposts": {
  "extent": 0.878
 }
};
