// stage.mjs: makes (or refreshes) a language's working copy of the project, i18n/<lang>/stage/, where the usual tools
// run unchanged on the translated script (i18n/PLAN.md).
//   node i18n/tools/stage.mjs [--lang=es]
// Then, from inside the stage:  node tools/voice.mjs, node tools/timeline.mjs, node render.mjs --chapter=1 --draft, ...
//
// The stage links to the English engine, scenes, tools and packages, so a fix there is a fix in every language. Its own:
//   script/     the translated script.yaml, chapters, the cold open's balloons, codes and sound cues, made here
//   assets/vo   the language's voice clips (i18n/<lang>/vo, committed like the English ones)
//   assets/qr   the codes' Still QR images, and src/gen/qr_images.js their index (i18n/<lang>/qr, committed)
//   audio/*.json  the voice's measurements (i18n/<lang>/audio, committed)
//   src/gen     its timelines, codes and window.I18N (src/gen/i18n.js, for i18n/src/i18n.js)
//   audio/ out/ site/public   what the tools make
//   studio.html the English studio with the i18n scripts added after the scene kit
// Refreshing keeps audio/, out/ and src/gen's timelines. It prints what's still in English.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, symlinkSync, lstatSync, readlinkSync, unlinkSync, rmSync, renameSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import YAML from 'yaml';
import { autoSpeech, compileRespellings, words, resolveAnchor, typedOf, meantOf, PACE } from '../../tools/script_lib.mjs';
import { translations, englishAnchors, samePlace, readYaml, optYaml, dirOf, langOf, args } from './i18n_lib.mjs';

const lang = langOf(args), L = dirOf(lang), S = `${L}/stage`;
// a language written without spaces (Japanese) has no words to count: a line's estimated length (tools/timeline.mjs,
// words at PACE.wpm) comes from its characters instead, at CPS spoken a second (Mandarin says fewer characters a second
// than Japanese, each a whole syllable), given as the words that take as long
const CJK = /^(ja|zh|ko)\b/.test(lang), CPS = /^zh\b/.test(lang) ? 4.5 : 6;
// a language whose glyphs the hand-lettering fonts lack (its studio.css lends them some): a sample to load them by
// before the first frame, and its labels fitted to the English widths they replace (i18n/src/i18n.js)
const GLYPHS = { ja: 'あア漢、。「」', hi: 'अआकक्षिह्रींॉ।', zh: '漢說臺、。「」', ko: '한글읽기《》' };
// German needs no glyphs, but its long compound words overrun the English widths too, and French and Italian run a fifth
// longer: all fitted the same way
const FIT = lang in GLYPHS || /^(de|fr|it)\b/.test(lang);
const countWords = s => CJK ? Math.round((s.replace(/\[[^\]]*\]/g, '').match(/[\p{L}\p{N}]/gu) || []).length / CPS * PACE.wpm / 60) : words(s);
const tr = translations(lang), strings = optYaml(`${L}/strings.yaml`, {});
const respell = compileRespellings(optYaml(`${L}/pronounce.yaml`, []));
// Curt's typos that survive (a misspelt name): the voice says what he meant
const typos = optYaml(`${L}/typos.yaml`, []), meant = (id, s) => typos.filter(t => t.line === id).reduce((a, t) => a.replace(typedOf(t.mark), meantOf(t.mark)), s);
const put = (f, s) => { mkdirSync(dirname(`${S}/${f}`), { recursive: true }); writeFileSync(`${S}/${f}`, s); };
const yaml = (f, head, v) => put(f, `# GENERATED by i18n/tools/stage.mjs (${lang}); do not edit. ${head}\n` + YAML.stringify(v, { lineWidth: 0 }));
function link(to, at) {   // at (in the stage) → to (from the project's root), relative
  const p = `${S}/${at}`, target = relative(dirname(resolve(p)), resolve(to));
  mkdirSync(dirname(p), { recursive: true });
  try { const st = lstatSync(p); if (st.isSymbolicLink() && readlinkSync(p) === target) return; if (st.isSymbolicLink()) unlinkSync(p); else rmSync(p, { recursive: true }); } catch { }
  symlinkSync(target, p);
}

// ---- the engine, linked ----
for (const f of ['node_modules', 'render.mjs', 'package.json', 'tools', 'docs', 'assets/ref', 'script/voices.yaml', 'script/beats.yaml'])
  if (existsSync(f)) link(f, f);
// the codes' Still QR images: the language's own once it has them (i18n/tools/qr_images.mjs makes them in
// i18n/<lang>/qr, writing through these links), else the English ones, which only the English links match
const OWN_QR = existsSync(`${L}/qr`);
link(OWN_QR ? `${L}/qr` : 'assets/qr', 'assets/qr');
mkdirSync(`${L}/vo`, { recursive: true }); link(`${L}/vo`, 'assets/vo');
// the sounds: the English ones, linked one by one, and the language's own (a sting whose length follows the timing),
// which tools/sfx.mjs makes in the stage and this moves to i18n/<lang>/sfx (committed)
const SFX = `${S}/assets/sfx`;
mkdirSync(`${L}/sfx`, { recursive: true });
if (existsSync(SFX) && lstatSync(SFX).isSymbolicLink()) unlinkSync(SFX);
mkdirSync(SFX, { recursive: true });
for (const f of readdirSync(SFX)) if (!lstatSync(`${SFX}/${f}`).isSymbolicLink()) renameSync(`${SFX}/${f}`, `${L}/sfx/${f}`);
for (const f of readdirSync(SFX)) if (!existsSync(`${SFX}/${f}`)) unlinkSync(`${SFX}/${f}`);   // a link to a sound since removed
for (const f of readdirSync('assets/sfx')) link(`assets/sfx/${f}`, `assets/sfx/${f}`);
for (const f of readdirSync(`${L}/sfx`)) link(`${L}/sfx/${f}`, `assets/sfx/${f}`);
// the voice's measurements (durations, lip sync, breaths), which the site's timings need: kept in i18n/<lang>/audio
// (committed, like the English audio/*.json) and linked in; the voice tools write through the links
mkdirSync(`${L}/audio`, { recursive: true }); mkdirSync(`${S}/audio`, { recursive: true });
for (const f of ['durations.json', 'sync.json', 'breaths.json', 'voice.json']) {
  const p = `${S}/audio/${f}`;
  if (existsSync(p) && !lstatSync(p).isSymbolicLink()) renameSync(p, `${L}/audio/${f}`);
  if (existsSync(`${L}/audio/${f}`)) link(`${L}/audio/${f}`, `audio/${f}`);
}
for (const f of readdirSync('src')) if (f !== 'gen') link(`src/${f}`, `src/${f}`);
link('i18n/src/i18n.js', 'src/i18n.js');
mkdirSync(`${S}/src/gen`, { recursive: true });
if (OWN_QR) link(`${L}/qr/qr_images.js`, 'src/gen/qr_images.js');
else if (!existsSync(`${S}/src/gen/qr_images.js`)) put('src/gen/qr_images.js', readFileSync('src/gen/qr_images.js', 'utf8'));
const studio = readFileSync('studio.html', 'utf8');
const hook = '<script src="src/scene_kit.js"></script>';
if (!studio.includes(hook)) throw new Error(`studio.html no longer loads ${hook}; update stage.mjs`);
// a language's own lettering (i18n/<lang>/studio.css: Japanese glyphs for the hand-lettering fonts), in the studio's head
const css = existsSync(`${L}/studio.css`);
if (css) link(`${L}/studio.css`, 'src/i18n.css');
put('studio.html', studio.replace(hook, `${hook}\n<script src="src/gen/i18n.js"></script>\n<script src="src/i18n.js"></script>`)
  .replace('</head>', css ? '<link rel="stylesheet" href="src/i18n.css">\n</head>' : '</head>'));

// ---- the script, translated ----
const en = readYaml('script/script.yaml'), byId = new Map(en.lines.map(l => [l.id, l]));
const untranslated = [], badAnchors = [];
const lines = en.lines.map(l => {
  const t = tr[l.id];
  if (!t?.text) { untranslated.push(l.id); return { ...l, untranslated: true }; }
  const out = { ...l, text: t.text };
  if (l.spoken) {
    out.speech = t.speech ?? autoSpeech(meant(l.id, t.text), respell).speech;
    out.speech_from = t.speech ? 'translation' : 'auto';
    out.words = countWords(out.speech);
  }
  for (const [p, a] of Object.entries(t.anchors || {})) if (!`${out.speech || ''}\n${out.text}`.toLowerCase().includes(a.toLowerCase())) badAnchors.push(`${l.id}: "${a}" (for "${p}")`);
  return out;
});
const es = new Map(lines.map(l => [l.id, l]));
yaml('script/script.yaml', 'The translated transcript, line by line.', { ...en, lines });

// every English phrase something is timed to → the translated line's words for it
const uses = englishAnchors(), anchors = {};
for (const [id, t] of Object.entries(tr)) for (const [p, a] of Object.entries(t.anchors || {})) (anchors[id] ||= {})[p] = a;   // scenes build some phrases at run time
let auto = 0;
const anchorOf = (id, p) => {
  const t = es.get(id), a = tr[id]?.anchors?.[p];
  if (a) return a;
  const s = t?.speech || t?.text || '';
  if (s.toLowerCase().includes(String(p).toLowerCase())) return p;
  const e = byId.get(id), got = samePlace(e?.speech || e?.text || '', p, s);
  if (got) auto++;
  return got;
};
for (const [id, ps] of Object.entries(uses)) for (const p of Object.keys(ps)) { const a = anchorOf(id, p); if (a && a !== p) (anchors[id] ||= {})[p] = a; }

// the chapters' titles, and the cold open's balloons
const ch = optYaml(`${L}/chapters.yaml`, {}), page = optYaml(`${L}/cold_open.yaml`, {});
yaml('script/chapters.yaml', 'Chapter titles translated.', readYaml('script/chapters.yaml').map(c => ({ ...c, title: ch[c.n] ?? c.title, ...(c.page ? { page: 'script/cold_open.yaml' } : {}) })));
yaml('script/cold_open.yaml', "The cold open's balloons, translated.", readYaml('script/cold_open.yaml').map(b => ({ ...b, ...(page[b.balloon] ? { say: page[b.balloon].say, who: page[b.balloon].who ?? b.who, ...(CJK ? { words: countWords(page[b.balloon].say) } : {}) } : {}) })));

// the codes: captions translated, each placed by line id, its cue in the translated words
// refs.yaml: { id: caption } or { id: { caption, url } }; wiki.yaml (wiki_links.mjs): the same Wikipedia article in the language
const refsTr = optYaml(`${L}/refs.yaml`, {}), wiki = optYaml(`${L}/wiki.yaml`, {});
const trRef = r => ({ ...r, ...(wiki[r.id] ? { url: wiki[r.id], en_url: r.url } : {}), ...(typeof refsTr[r.id] === 'string' ? { caption: refsTr[r.id] } : refsTr[r.id] || {}) });
// refs_added.yaml: codes only this language's film has (its note on the translation), in the same form as refs.yaml
yaml('script/refs.yaml', 'Codes with translated captions and cues.', [...readYaml('script/refs.yaml'), ...optYaml(`${L}/refs_added.yaml`, [])].map(r => {
  const o = trRef(r);
  if (r.at && !/^T\d\d\.|^MAD\./.test(r.at)) { const l = resolveAnchor(r, en.lines, byId); if (l) o.at = l.id; }
  if (r.cue && /^T\d\d\./.test(o.at)) o.cue = anchorOf(o.at, r.cue) ?? r.cue;
  return o;
}));
// the sounds: each cue's phrase in the translated words
const sfx = readYaml('script/sfx.yaml');
for (const c of sfx.cues || []) for (const k of ['at', 'until'])
  if (Array.isArray(c[k]) && typeof c[k][1] === 'string' && c[k][1] !== '@end') c[k] = [c[k][0], anchorOf(c[k][0], c[k][1]) ?? c[k][1], ...c[k].slice(2)];
yaml('script/sfx.yaml', 'Sound cues timed to the translated words.', sfx);
// Curt's typos, where a slip survives translation (a misspelt name), marked in the translated text
yaml('script/typos.yaml', "Curt's typos, in the translation.", optYaml(`${L}/typos.yaml`, []));
// the site: under its language; its film is the language's own (i18n/<lang>/site.yaml's film), else on its way
const site = readYaml('script/site.yaml'), siteTr = optYaml(`${L}/site.yaml`, {});
yaml('script/site.yaml', 'The site, under its language.', { ...site, base: `${site.base}${lang}/`, film: { repo: site.film?.repo, ...(siteTr.film || {}) } });
// the site's own words (tools/build_site.mjs's SITE_WORDS), translated
yaml('script/site_strings.yaml', "The site's own words, translated.", optYaml(`${L}/site_strings.yaml`, {}));
// the YouTube upload's words (tools/youtube.mjs's YOUTUBE_WORDS), translated
yaml('script/youtube_strings.yaml', "The YouTube upload's words, translated.", optYaml(`${L}/youtube_strings.yaml`, {}));
for (const f of ['pronounce.yaml', 'overrides.yaml']) yaml(`script/${f}`, 'Unused in a translation (see i18n/<lang>/pronounce.yaml).', []);
// the site's thumbnail, the language's own (i18n/<lang>/site/thumbnail.jpg, from its thumbnail_swarm.jpg)
if (existsSync(`${L}/site/thumbnail.jpg`)) link(`${L}/site/thumbnail.jpg`, 'site/thumbnail.jpg');
// the explainers' codes: from the language's explainers (i18n/<lang>/site/notes, linked in as the stage's site/notes),
// as tools/build_site.mjs writes them; until those exist, the English ones with their captions translated
const NOTES = `${L}/site/notes`;
if (existsSync(NOTES)) {
  link(NOTES, 'site/notes');
  const explained = optYaml(`${L}/site_strings.yaml`, {}).explained || 'Explained';
  const base = `${site.base}${lang}/`;
  yaml('script/notes_refs.yaml', "The explainers' codes, from the language's explainers.", readdirSync(NOTES).filter(f => f.endsWith('.md')).sort().map(f => {
    const m = YAML.parse(readFileSync(`${NOTES}/${f}`, 'utf8').match(/^---\n([\s\S]*?)\n---\n/)[1]);
    return { id: `note-${m.id}`, url: `${base}${site.notes}${m.id}/`, caption: `${explained}: ${m.title}`, origin: 'note', ch: m.ch, at: m.at, ...(m.cue ? { cue: m.cue } : {}), mode: m.mode || 'shelf', style: 'note' };
  }));
} else yaml('script/notes_refs.yaml', "The explainers' codes, captions translated.", readYaml('script/notes_refs.yaml').map(trRef));
// the conversation as the site serves it (conversation.txt): the translated transcript, turn by turn, in the form of
// script/conversation.md
{
  const md = [], turns = [];
  for (const l of lines) {
    const turn = l.id.split('.').slice(0, 2).join('.'), t = turns.at(-1);
    if (t && t.turn === turn) t.md += (l.kind === 'item' && t.last === 'item' || l.kind === 'source' && t.last === 'source' ? '\n' : '\n\n') + l.text, t.last = l.kind;
    else turns.push({ turn, speaker: l.speaker, md: l.text, last: l.kind });
  }
  let n = null;
  for (const t of turns) { const tn = t.turn.split('.')[0]; if (tn !== n) { n = tn; md.push(`## ${tn}`); } md.push(`### ${t.speaker === 'curt' ? 'Curt' : 'Claude'}`, t.md); }
  const p = `${S}/script/conversation.md`;
  try { if (lstatSync(p).isSymbolicLink()) unlinkSync(p); } catch { }
  const head = optYaml(`${L}/site_strings.yaml`, {}).transcript_head || readFileSync('script/conversation.md', 'utf8').split('\n## ')[0].trim();
  put('script/conversation.md', `${head}\n\n${md.join('\n\n')}\n`);
}

// ---- what the studio needs ----
const balloons = Object.fromEntries(Object.entries(page).filter(([, b]) => b.lines).map(([k, b]) => [k, b.lines]));
put('src/gen/i18n.js', `// GENERATED by i18n/tools/stage.mjs; do not edit.\nwindow.I18N = ${JSON.stringify({
  lang, cjk: CJK && !/^ko\b/.test(lang), ...(/^ko\b/.test(lang) ? { particles: true } : {}),   // Korean is timed by syllables but spaced and wrapped like English
  ...(GLYPHS[lang] ? { glyphs: GLYPHS[lang] } : {}), ...(FIT ? { fit: true } : {}), strings, keep: Object.keys(strings).filter(k => strings[k] === k), anchors, balloons,
  page: Object.values(balloons).map(ls => ls.join(' ').replace(/\*/g, '')).join('\n'),
  en: Object.fromEntries(en.lines.filter(l => uses[l.id] || anchors[l.id]).map(l => [l.id, l.speech || l.text])),
  tables: Object.fromEntries(en.lines.filter(l => l.kind === 'table').map(l => [l.id, l.text])),   // read in English; cells lettered through strings
})};\n`);

// ---- report ----
const byCh = {}; for (const id of untranslated) { const c = byId.get(id).ch; byCh[c] = (byCh[c] || 0) + 1; }
console.log(`${S}: ${lines.length - untranslated.length}/${lines.length} lines translated` +
  (untranslated.length ? ` (still English, by chapter: ${Object.entries(byCh).map(([c, n]) => `${c}: ${n}`).join(', ')})` : ''));
console.log(`  ${Object.keys(strings).length} lettered strings; ${auto} cue phrases placed by position (no anchor given)`);
const allRefs = [...readYaml('script/refs.yaml'), ...readYaml('script/notes_refs.yaml')], capCh = {};
for (const r of allRefs) if (refsTr[r.id] == null) { const c = r.ch ?? byId.get(r.at)?.ch ?? '?'; capCh[c] = (capCh[c] || 0) + 1; }
const nCap = Object.values(capCh).reduce((a, b) => a + b, 0);
console.log(`  ${allRefs.length - nCap}/${allRefs.length} code captions translated` + (nCap ? ` (still English, by chapter: ${Object.entries(capCh).map(([c, n]) => `${c}: ${n}`).join(', ')})` : ''));
if (badAnchors.length) { console.error(`anchors not in their line:\n  ${badAnchors.join('\n  ')}`); process.exit(1); }
